### ISSUE TITLE
Camera loads a static image

### ISSUE THREAD

**Issue by krel99** [antoniocasino/movenet-space-invaders#1]
I tried to install this game. The camera would only take a snapshot.

Console Error: Uncaught (in promise) OverconstrainedError in movenet-space-invade…n.up.railway.app/:1

**Comment by antoniocasino** [comment]
What OS and browser are you using?
I currently tested it on Windows OS , with Chrome 120 and Edge 120 
Make sure to  enable the camera in the browser.
OverconstrainedError seems like an error related to the camera

**Comment by krel99** [comment]
Linux (PopOS) with Brave. 
I tried again and instead of giving it permission till I close the site I gave it 24h and it appears to work. Interesting.

**Comment by antoniocasino** [comment]
As far as I understood the issue is related to your camera browser config.
I will close the issue
